// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmUuvfDvng6dGyHbwKlLytaabEO3KB2g4',
    appId: '1:522125922842:web:c5fb388f874c64240df7a3',
    messagingSenderId: '522125922842',
    projectId: 'whatsapp-backend-chat',
    authDomain: 'whatsapp-backend-chat.firebaseapp.com',
    storageBucket: 'whatsapp-backend-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZifmM_gKsbqMQ7D4x-ZENk7nexhVUKCw',
    appId: '1:522125922842:android:d04af8c3642463520df7a3',
    messagingSenderId: '522125922842',
    projectId: 'whatsapp-backend-chat',
    storageBucket: 'whatsapp-backend-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANHXGOGaJf3yYErNiypK8JEMaqn7bfVQY',
    appId: '1:522125922842:ios:796abd406bfc764e0df7a3',
    messagingSenderId: '522125922842',
    projectId: 'whatsapp-backend-chat',
    storageBucket: 'whatsapp-backend-chat.appspot.com',
    iosClientId: '522125922842-fd3vfhrb0fi47jn65g6qviuhrs9u8tkf.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANHXGOGaJf3yYErNiypK8JEMaqn7bfVQY',
    appId: '1:522125922842:ios:796abd406bfc764e0df7a3',
    messagingSenderId: '522125922842',
    projectId: 'whatsapp-backend-chat',
    storageBucket: 'whatsapp-backend-chat.appspot.com',
    iosClientId: '522125922842-fd3vfhrb0fi47jn65g6qviuhrs9u8tkf.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.whatsappClone',
  );
}
